export const MAIN_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CATALOG_ROUTE='/catalog'
export const REQUEST_ROUTE='/request'
export const JOB_ROUTE='/catalog/'